export const PET_METRICS_CACHE_TTL_SECONDS = 300;
export const PET_METRICS_CACHE_TTL_MS = PET_METRICS_CACHE_TTL_SECONDS * 1000;
export const PET_METRICS_CACHE_CONTROL = `public, max-age=${PET_METRICS_CACHE_TTL_SECONDS}, s-maxage=${PET_METRICS_CACHE_TTL_SECONDS}`;
