export const PET_METRICS_CACHE_TTL_SECONDS = 300;
export const PET_METRICS_CACHE_TTL_MS = PET_METRICS_CACHE_TTL_SECONDS * 1000;
export const PET_METRICS_STALE_WHILE_REVALIDATE_SECONDS = 900;
export const PET_METRICS_CACHE_CONTROL = `public, max-age=${PET_METRICS_CACHE_TTL_SECONDS}, s-maxage=${PET_METRICS_CACHE_TTL_SECONDS}, stale-while-revalidate=${PET_METRICS_STALE_WHILE_REVALIDATE_SECONDS}`;
